package com.scaffold.webservice.generateSource;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-26T05:03:46.646+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://inf.server.webservice.scaffold.com/", name = "ISurveyService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISurveyService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "vote", targetNamespace = "http://inf.server.webservice.scaffold.com/", className = "com.scaffold.webservice.generateSource.Vote")
    @WebMethod
    @ResponseWrapper(localName = "voteResponse", targetNamespace = "http://inf.server.webservice.scaffold.com/", className = "com.scaffold.webservice.generateSource.VoteResponse")
    public java.lang.String vote(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
