package com.scaffold.webservice.generateSource;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-26T05:03:46.724+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "ISurveyServiceService", 
                  wsdlLocation = "http://localhost:8090/scaffold-webservice/SurveyWebService?wsdl",
                  targetNamespace = "http://inf.server.webservice.scaffold.com/") 
public class ISurveyServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inf.server.webservice.scaffold.com/", "ISurveyServiceService");
    public final static QName ISurveyServicePort = new QName("http://inf.server.webservice.scaffold.com/", "ISurveyServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/scaffold-webservice/SurveyWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ISurveyServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/scaffold-webservice/SurveyWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISurveyServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISurveyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISurveyServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ISurveyService
     */
    @WebEndpoint(name = "ISurveyServicePort")
    public ISurveyService getISurveyServicePort() {
        return super.getPort(ISurveyServicePort, ISurveyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISurveyService
     */
    @WebEndpoint(name = "ISurveyServicePort")
    public ISurveyService getISurveyServicePort(WebServiceFeature... features) {
        return super.getPort(ISurveyServicePort, ISurveyService.class, features);
    }

}
